SELECT
    p.CD_PRODUTO
    , p.CD_ESPECIE
    , p.DT_CADASTRO
    , p.DT_ULTIMA_ENTRADA
    , p.HR_ULTIMA_ENTRADA
    , p.QT_ESTOQUE_ATUAL
    , p.QT_ULTIMA_ENTRADA
    , p.VL_ULTIMA_ENTRADA
    , p.VL_CUSTO_MEDIO
    , p.VL_ULTIMA_CUSTO_REAL
    , p.DS_PRODUTO
    , p.DS_PRODUTO_RESUMIDO
FROM DBAMV.PRODUTO p
